spring.application.name=kontrolltoo
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/wordlength
spring.datasource.username=postgres
spring.datasource.password=1234